steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/seekr-62d4d/ppe-detection', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/seekr-62d4d/ppe-detection']